var ds = [

    {
        brand: 'phone',
        id: 'ip6s',
        img: 'img/phone_iphone/iphone6s.png',
        name: 'IPHONE 6S 32GB',
        price: '$449',
        display: 'LED-backlit IPS LCD, 4.7, Retina HD',
        dimensions: '158 X 78 X 7.5',
        os: '10',
        camera: '5 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A9 2 Core 64-bit',
        ram: '2g',
        memory: '32 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver, Zoom, Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions, AssistiveTouch, Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2750 mAh'
    },

    {
        brand: 'phone',
        id: 'ip6s 256',
        img: 'img/phone_iphone/iphone6s_product2.png',
        name: 'IPHONE 6S 256GB',
        price: '$549',
        display: 'LED-backlit IPS LCD, 4.7, Retina HD',
        dimensions: '158 X 78 X 7.5',
        os: '10',
        camera: '5 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A9 2 Core 64-bit',
        ram: '2g',
        memory: '256 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver, Zoom, Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions, AssistiveTouch, Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2750 mAh'
    },

    {
        brand: 'phone',
        id: 'ip7',
        img: 'img/phone_iphone/iphone 7plus_product2.jpg',
        name: 'IPhone 7 Plus 32GB',
        price: '$669',
        display: 'LED-backlit IPS LCD, 5.5, Retina HD',
        dimensions: '158.2 x 77.9 x 7.3 mm',
        os: '11',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A9 2 Core 64-bit',
        ram: '3 GB',
        memory: '32 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver, Zoom, Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions, AssistiveTouch, Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2900 mAh'
    },


    {
        brand: 'phone',
        id: 'ip7s',
        img: 'img/phone_iphone/iphone8.png',
        name: 'Iphone 8 64GB',
        price: '$869',
        display: 'LED-backlit IPS LCD, 4.7, Retina HD',
        dimensions: '158.2 x 77.9 x 7.3 mm',
        os: '11',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A11 Bionic',
        ram: '3 GB',
        memory: '64 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver, Zoom, Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions, AssistiveTouch, Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2900 mAh'
    },


    {
        brand: 'phone',
        id: 'iphone8256',
        img: 'img/phone_iphone/iphone8_product1.jpg',
        name: 'IPhone 8 256GB',
        price: '$449',
        display: 'LED-backlit IPS LCD, 5.5, Retina HD',
        dimensions: '158 X 78 X 7.5',
        os: '11',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A9 2 Core 64-bit',
        ram: '2g',
        memory: '256 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver, Zoom, Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions, AssistiveTouch, Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2750 mAh'
    },
    {
        brand: 'phone',
        id: '8plus256',
        img: 'img/phone_iphone/iphone8_plus.jpg',
        name: 'Iphone 8plus 256GB',
        price: '$1019',
        display: 'LED-backlit IPS LCD, 4.7, Retina HD',
        dimensions: '158 X 78 X 7.5',
        os: '11',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A11 Bionic',
        ram: '3 GB',
        memory: '256 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver, Zoom, Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions, AssistiveTouch, Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2900 mAh'
    },
    {
        brand: 'phone',
        id: 'iphone8plus',
        img: 'img/phone_iphone/iphone8plus.png',
        name: 'IPhone 8 plus 64 GB ',
        price: '$989',
        display: 'LED-backlit IPS LCD, 5.5, Retina HD',
        dimensions: '158 X 78 X 7.5',
        os: '11',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A11 Bionic',
        ram: '3 g',
        memory: '64 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver, Zoom, Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions, AssistiveTouch, Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2750 mAh'
    },
    {
        brand: 'phone',
        id: 'ipx64',
        img: 'img/phone_iphone/iphone11_1.jpg',
        name: 'Iphone 11 ProMax 512GB',
        price: '$1790',
        display: 'OLED, 6.5", Super Retina XDR',
        dimensions: '158 X 77.8 X 8.1',
        os: 'iOS 13',
        camera: '12 MP & 3 camera 12 MP (4 camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 24 fps, 30 fps, or 60 fps',
        cpu: '	Apple A13 Bionic  ',
        ram: '4 GB',
        memory: '512 GB',
        sim_card: '1 eSIM & 1 Nano SIM',
        wifi: '	Dual-band, Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver, Zoom, Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions, AssistiveTouch, Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3969 mAh'
    },
    {
        brand: 'phone',
        id: 'ipx256',
        img: 'img/phone_iphone/iphoneX.png',
        name: 'IPhone X 256 GB ',
        price: '$1189',
        display: 'LED-backlit IPS LCD, 5.8, Retina HD',
        dimensions: '158 X 78 X 7.5',
        os: '11',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A11 Bionic',
        ram: '3 GB',
        memory: '256 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver, Zoom, Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions, AssistiveTouch, Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3100 mAh'
    },

    ///phone_samsung
    {
        brand: 'phone',
        id: 'note8',
        img: 'img/phone_samsung/Samsung Galaxy Note 8.png',
        name: 'Galaxy Note 8 ',
        price: '$889',
        display: 'Super AMOLED, 6.3, Quad HD (2k)',
        dimensions: '162.5 x 74.8 x 8.6',
        os: 'Android 7.1',
        camera: '8 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Exynos 8895 8-core 64-bit',
        ram: '4 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3300 mAh'
    },

    {
        brand: 'phone',
        id: 'notefe',
        img: 'img/phone_samsung/Samsung Galaxy Note FE.png',
        name: 'Galaxy Note FE ',
        price: '$806',
        display: 'Super AMOLED, 5.7, Quad HD (2k)',
        dimensions: '153.5 x 73.9 x 7.9 ',
        os: 'Android 7.0',
        camera: '5 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Exynos 8890 8 core 64-bit',
        ram: '6 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3200 mAh'
    },

    {
        brand: 'phone',
        id: 'c9pro',
        img: 'img/phone_samsung/Samsung Galaxy C9 Pro.png',
        name: 'Galaxy C9 Pro ',
        price: '$395,8',
        display: 'Super AMOLED, 6, Quad HD (2k)',
        dimensions: '162.9 x 80.7 x 6.9',
        os: 'Android 6.0',
        camera: '16 MP & 16 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Snapdragon 653 8 core 64-bit',
        ram: '6 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '4000 mAh'
    },

    {
        brand: 'phone',
        id: 's8plus',
        img: 'img/phone_samsung/Samsung Galaxy S8 Plus.png',
        name: 'Galaxy S8 Plus ',
        price: '$954',
        display: 'Super AMOLED, 6.2, Quad HD (2k)',
        dimensions: '159.5 mm - 73.4 mm - 8.1 mm',
        os: 'Android 7.0',
        camera: '8 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Exynos 8895 8 core 64-bit',
        ram: '4 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3500 mAh'
    },

    {
        brand: 'phone',
        id: 's8',
        img: 'img/phone_samsung/Samsung Galaxy S8.png',
        name: 'Galaxy S8 ',
        price: '$854',
        display: 'Super AMOLED, 5.8, Quad HD (2k)',
        dimensions: '148.9 mm - 68.1 mm - 8 mm',
        os: 'Android 7.0',
        camera: '8 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Exynos 8895 8 core 64-bit',
        ram: '4 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3000 mAh'
    },

    {
        brand: 'phone',
        id: 'a7',
        img: 'img/phone_samsung/Samsung Galaxy A7.png',
        name: 'Galaxy A7 ',
        price: '$420',
        display: 'Super AMOLED, 5.7, Quad HD (2k)',
        dimensions: '156.8 mm - 77.6 mm - 7.9 mm',
        os: 'Android 6.0',
        camera: '16 MP & 16 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Exynos 7880 8 core 64-bit',
        ram: '3 GB',
        memory: '32 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3600 mAh'
    },

    {
        brand: 'phone',
        id: 'j7',
        img: 'img/phone_samsung/Samsung Galaxy J7+.png',
        name: 'Galaxy J7 ',
        price: '$363',
        display: 'Super AMOLED, 5.5, Quad HD (2k)',
        dimensions: '152.4 mm - 74.7 mm - 7.9 mm',
        os: 'Android 6.0',
        camera: '16 MP & 13 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Mediatek Helio P25 Lite 8 core',
        ram: '4 GB',
        memory: '32 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3000 mAh'
    },

    {
        brand: 'phone',
        id: 'a5',
        img: 'img/phone_samsung/Samsung Galaxy A5.png',
        name: 'Galaxy A5 ',
        price: '$330',
        display: 'Super AMOLED, 5.2, Quad HD (2k)',
        dimensions: '146.1 mm - 71.4 mm - 7.9 mm',
        os: 'Android 6.0',
        camera: '16 MP & 16 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Exynos 7880 8 core 64-bit',
        ram: '3 GB',
        memory: '32 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3000 mAh'
    },

    ////////phone_sony


    {
        brand: 'phone',
        id: 'xzpr',
        img: 'img/phone_sony/Sony Xperia_XZ.png',
        name: 'Xperia XZ Premium ',
        price: '$629.99',
        display: 'IPS LCD, 5.5, Ultra HD (4K)',
        dimensions: '156.00 x 77.00 x 7.90',
        os: 'Android 7.1',
        camera: '13 MP & 19 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Qualcomm Snapdragon 835',
        ram: '4 GB',
        memory: '32 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3230 mAh'
    },

    {
        brand: 'phone',
        id: 'xzdu',
        img: 'img/phone_sony/Sony Xperia XZ Dual.png',
        name: 'Xperia XZ Dual ',
        price: '$336.44',
        display: 'IPS LCD, 5.5, Ultra HD (4K)',
        dimensions: '146 x 72x 8.1',
        os: 'Android 7.0',
        camera: '13 MP & 23 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Snapdragon 820',
        ram: '3 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2900 mAh'
    },


    {
        brand: 'phone',
        id: 'xau',
        img: 'img/phone_sony/SonyXperiaXA1Ultra.png',
        name: 'Xperia XA1 Ultra ',
        price: '$342.99',
        display: 'IPS LCD, 6.0, Ultra HD (4K)',
        dimensions: '165 x 79 x 8.1',
        os: 'Android 7.0',
        camera: '13 MP & 23 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Mediatek Helio P20',
        ram: '4 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2700 mAh'
    },

    {
        brand: 'phone',
        id: 'xzprep',
        img: 'img/phone_sony/Sony Xperia XZ Premium Pink Gold.png',
        name: 'Premium Pink Gold',
        price: '$609.99',
        display: 'IPS LCD, 5.5, Ultra HD (4K)',
        dimensions: '156.00 x 77.00 x 7.90',
        os: 'Android 7.1',
        camera: '13 MP & 19 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Qualcomm Snapdragon 835',
        ram: '4 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3230 mAh'
    },

    {
        brand: 'phone',
        id: 'xz1',
        img: 'img/phone_sony/Sony Xperia XZ1.png',
        name: ' Sony Xperia XZ1 ',
        price: '$635',
        display: 'IPS LCD, 5.2, Ultra HD (4K)',
        dimensions: '148 mm - 73.4 mm - 7.4 mm',
        os: 'Android 8.0',
        camera: '13 MP & 19 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Qualcomm Snapdragon 835',
        ram: '4 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2700 mAh'
    },

    {
        brand: 'phone',
        id: 'xzs',
        img: 'img/phone_sony/Sony Xperia XZs.png',
        name: ' Sony Xperia XZs ',
        price: '$579',
        display: 'IPS LCD, 5.2, Ultra HD (4K)',
        dimensions: '146 mm - 72 mm -8.1 mm',
        os: 'Android 7.0',
        camera: '13 MP & 19 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Snapdragon 820 4 core 64-bit',
        ram: '4 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2900 mAh'
    },


    {
        brand: 'phone',
        id: 'xx',
        img: 'img/phone_sony/Sony Xperia X.png',
        name: ' Sony Xperia X',
        price: '$321',
        display: 'IPS LCD, 5, Ultra HD (4K)',
        dimensions: '142.7 mm - 69.4 mm - 7.9 mm',
        os: 'Android 6.0',
        camera: '13 MP & 23 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Snapdragon 650 6 core 64-bit',
        ram: '3 GB',
        memory: '64 GB',
        sim_card: '2 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2620 mAh'
    },
    /////tablet
    {
        brand: 'tablet',
        id: 'pad1',
        img: 'img/tablet_ipad/iPad Wifi Cellular_1.jpg',
        name: 'iPad Pro 10.5 inch Wifi Cellular 64GB',
        price: '$779',
        display: 'LED backlit LCD, 10.5',
        dimensions: '250.6 x 174.1 x 6.1',
        os: 'IOS 10',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A10X 6 core 64-bit',
        ram: '4 GB',
        memory: '64 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3200 mAh'
    },

    {
        brand: 'tablet',
        id: 'pad2',
        img: 'img/tablet_ipad/iPad Pro.png',
        name: 'iPad Pro 10.5 inch Wifi 64GB',
        price: '$739',
        display: 'LED backlit LCD, 10.5',
        dimensions: '250.6 x 174.1 x 6.1',
        os: 'IOS 10',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A10X 6 core 64-bit',
        ram: '4 GB',
        memory: '64 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3200 mAh'
    },

    {
        brand: 'tablet',
        id: 'pad3',
        img: 'img/tablet_ipad/iPad Wifi Cellular.png',
        name: 'iPad Wifi Cellular 128GB',
        price: '$559',
        display: 'LED backlit LCD, 10.5',
        dimensions: '250.6 x 174.1 x 6.1',
        os: 'IOS 10',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A9 2 core 64-bit, 1.84 GHz',
        ram: '4 GB',
        memory: '128GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3390 mAh'
    },

    {
        brand: 'tablet',
        id: 'pad3',
        img: 'img/tablet_ipad/iPad Wifi Cellular.png',
        name: 'iPad Wifi Cellular 32GB',
        price: '$399',
        display: 'LED backlit LCD, 10.5',
        dimensions: '250.6 x 174.1 x 6.1',
        os: 'IOS 10',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A9 2 core 64-bit, 1.84 GHz',
        ram: '4 GB',
        memory: '32 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3390 mAh'
    },

    {
        brand: 'tablet',
        id: 'pad4',
        img: 'img/tablet_ipad/iPad Mini 4 Wifi 128GB_1.jpg',
        name: 'iPad Wifi 32 GB',
        price: '$429',
        display: 'LED backlit LCD, 9.7 ',
        dimensions: '250.6 x 174.1 x 6.1',
        os: 'IOS 10',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A9 2 core 64-bit, 1.84 GHz',
        ram: '2 GB',
        memory: '32 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3190 mAh'
    },

    {
        brand: 'tablet',
        id: 'pad5',
        img: 'img/tablet_ipad/iPad Mini 4 Wifi 128GB_1.jpg',
        name: 'iPad Wifi 128GB',
        price: '$559',
        display: 'LED backlit LCD, 9.7 ',
        dimensions: '250.6 x 174.1 x 6.1',
        os: 'IOS 10',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A9 2 core 64-bit, 1.84 GHz',
        ram: '2 GB',
        memory: '128 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3290 mAh'
    },


    {
        brand: 'tablet',
        id: 'pad6',
        img: 'img/tablet_ipad/ipad_mini_wifi.jpg',
        name: 'iPad Mini 4 Wifi 128GB',
        price: '$479',
        display: 'LED backlit LCD, 6.1 ',
        dimensions: '203.2mm - 134.8mm - 6.1mm',
        os: 'IOS 10',
        camera: '7 MP & 12 MP (2camera)',
        videocall: 'yes',
        video_recording: '4K video recording at 30 fps',
        cpu: 'Apple A8 2 core 64-bit, 1.5 GHz',
        ram: '2 GB',
        memory: '128 GB',
        sim_card: '1 Nano SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '3100 mAh'
    },

    ////tablet_asus

    {
        brand: 'tablet',
        id: 'tas1',
        img: 'img/tablet_asus/Asus Zenfone Go ZB690KG.png',
        name: 'Asus Zenfone Go ZB690KG',
        price: '$329',
        display: 'IPS LCD, 6.9 ',
        dimensions: '187.9x101.4x8.85',
        os: 'Android 5.1',
        camera: '2 MP & 8 MP (2camera)',
        videocall: 'yes',
        video_recording: '720px video recording at 30 fps',
        cpu: 'Qualcomm Snapdragon 200 4 core 32bit, 1.2 GHz',
        ram: '1 GB',
        memory: '8 GB',
        sim_card: '1 Micro SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2800 mAh'
    },


    {
        brand: 'tablet',
        id: 'tas2',
        img: 'img/tablet_asus/ASUS ZenPad C 7.0 (Z170CG).png',
        name: 'ASUS ZenPad 7.0 (Z370CG)',
        price: '$125',
        display: 'IPS LCD, 7 ',
        dimensions: '187.9x101.4x8.85',
        os: 'Android 5.1 ',
        camera: '2 MP & 8 MP (2camera)',
        videocall: 'yes',
        video_recording: '720px video recording at 30 fps',
        cpu: 'Qualcomm Snapdragon 200 4 core 32bit, 1.2 GHz',
        ram: '2 GB',
        memory: '16 GB',
        sim_card: '1 Micro SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2800 mAh'
    },


    {
        brand: 'tablet',
        id: 'tas3',
        img: 'img/tablet_asus/ASUS ZenPad C 7.0_1.jpg',
        name: 'ASUS ZenPad C 7.0 (Z170CG)',
        price: '$225',
        display: 'IPS LCD, 7 ',
        dimensions: '187.9x101.4x8.85',
        os: 'Android 5.0 ',
        camera: '2 MP & 8 MP (2camera)',
        videocall: 'yes',
        video_recording: '720px video recording at 30 fps',
        cpu: 'Qualcomm Snapdragon 200 4 core 32bit, 1.2 GHz',
        ram: '1 GB',
        memory: '8 GB',
        sim_card: '1 Micro SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2800 mAh'
    },


    {
        brand: 'tablet',
        id: 'tas4',
        img: 'img/tablet_asus/ASUS P008_1.jpg',
        name: 'ASUS P008',
        price: '$205',
        display: 'IPS LCD, 7 ',
        dimensions: '187.9x101.4x8.85',
        os: 'Android 6.0 ',
        camera: '1.8 MP & 7 MP (2camera)',
        videocall: 'yes',
        video_recording: '720px video recording at 30 fps',
        cpu: 'Qualcomm, 1.8 GHz',
        ram: '1 GB',
        memory: '8 GB',
        sim_card: '1 Micro SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2690 mAh'
    },

    //////////tabletsamsung

    {
        brand: 'tablet',
        id: 'tasa1',
        img: 'img/tablet_samsung/Samsung Galaxy Tab A 8.0.png',
        name: 'Samsung Galaxy Tab A 8.0',
        price: '$200',
        display: 'PLS TFT, 8 ',
        dimensions: '1280 x 800 pixels',
        os: 'Android 7.0 ',
        camera: '5 MP & 8 MP (2camera)',
        videocall: 'yes',
        video_recording: '720px video recording at 30 fps',
        cpu: 'Qualcomm MSM8917, 1.4 GHz',
        ram: '2 GB',
        memory: '16 GB',
        sim_card: '1 Micro SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2990 mAh'
    },


    {
        brand: 'tablet',
        id: 'tasa2',
        img: 'img/tablet_samsung/Samsung Galaxy Tab E 9.6_1.jpg',
        name: 'Samsung Galaxy Tab E 9.6',
        price: '$169.89',
        display: 'PLS TFT, 9.6 ',
        dimensions: '241.9x149.5x8.5',
        os: 'Android 4.0 ',
        camera: '2 MP & 5 MP (2camera)',
        videocall: 'yes',
        video_recording: '720px video recording at 30 fps',
        cpu: 'Spreadtrum 4 core',
        ram: '1.5 GB',
        memory: '8 GB',
        sim_card: '1 Micro SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2100 mAh'
    },


    {
        brand: 'tablet',
        id: 'tasa3',
        img: 'img/tablet_samsung/Samsung Galaxy Tab A6 7.0.png',
        name: 'Samsung Galaxy Tab A6 7.0',
        price: '$159.89',
        display: 'PLS TFT, 7.0 ',
        dimensions: '186.9x108.8x8.7',
        os: 'Android 5.1 ',
        camera: '2 MP & 5 MP (2camera)',
        videocall: 'yes',
        video_recording: '720px video recording at 30 fps',
        cpu: 'Spreadtrum 4 core',
        ram: '1.5 GB',
        memory: '8 GB',
        sim_card: '1 Micro SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2050 mAh'
    },

    {
        brand: 'tablet',
        id: 'tasa4',
        img: 'img/tablet_samsung/Samsung Galaxy Tab A6 10.1.png',
        name: 'Samsung Galaxy Tab A6  10.1 inch',
        price: '$159.89',
        display: 'PLS TFT, 10.1 ',
        dimensions: '254.30 x 164.20 x 8.20 mm',
        os: 'Android 6.0',
        camera: '2 MP & 8 MP (2camera)',
        videocall: 'yes',
        video_recording: '720px video recording at 30 fps',
        cpu: 'Exynos 7870 8 core 1.6ghz',
        ram: '3 GB',
        memory: '16 GB',
        sim_card: '1 Micro SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2550 mAh'
    },


    {
        brand: 'tablet',
        id: 'tasa5',
        img: 'img/tablet_samsung/Samsung Galaxy Tab E 9.6.png',
        name: 'Samsung Galaxy Tab A6 10.1 inch',
        price: '$165.89',
        display: 'PLS TFT, 10.1 ',
        dimensions: '254.30 x 164.20 x 8.20 mm',
        os: 'Android 6.0',
        camera: '5 MP & 8 MP (2camera)',
        videocall: 'yes',
        video_recording: '720px video recording at 30 fps',
        cpu: 'Exynos 7870 8 core 1.6ghz',
        ram: '3 GB',
        memory: '16 GB',
        sim_card: '1 Micro SIM',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Google, Google and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2550 mAh'
    },

    //////////////////////////////////LAptop///////////////////
    {
        brand: 'laptop',
        id: 'lapmac1',
        img: 'img/laptop_apple/apple-macbook-pro-touch-mpxv2sa-a-xam-avar-450x300.jpg',
        name: 'Macbook Air MQD32SA/A',
        price: '$999',
        display: '13.3 inch, WXGA+(1440 x 900) ',
        dimensions: '325 mm - 227 mm -17 mm',
        os: 'Mac OS',
        camera: '5 MP',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i5 Broadwell, 1.80 GHz',
        ram: '8 GB, DDR3L(On board), 1600 MHz ',
        memory: 'SSD: 128 GB',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '26000 mAh'
    },


    {
        brand: 'laptop',
        id: 'lapmac2',
        img: 'img/laptop_apple/apple-macbook-air-mqd32sa-a.jpg',
        name: 'Macbook Air MQD42SA ',
        price: '$1219',
        display: '13.3 inch, WXGA+(1440 x 900) ',
        dimensions: '325 mm - 227 mm -17 mm',
        os: 'Mac OS',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i5 Broadwell, 1.80 GHz',
        ram: '8 GB, DDR3L(On board), 1600 MHz ',
        memory: 'SSD: 256 GB',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '22000 mAh'
    },




    {
        brand: 'laptop',
        id: 'lapmac4',
        img: 'img/laptop_apple/apple-macbook-pro-mpxt2sa-a-i5-7360u-xam-dai-dien-4y-450x300-450x300.jpg',
        name: 'Macbook 12 MLHF2   ',
        price: '$1,519',
        display: '12 inch, Retina (2304 x 1440)    ',
        dimensions: '304.1 mm - 212.4 mm -  14.9 mm ',
        os: 'Mac OS',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core M, M5, 1.20 GHz  ',
        ram: '8 GB, DDR3L(On board), 1866 MHz ',
        memory: 'SSD: 512 GB',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2750 mAh'
    },

    {
        brand: 'laptop',
        id: 'lapmac3',
        img: 'img/laptop_apple/apple-macbook-pro-mpxt2sa-a-i5-7360u-xam-dai-dien-4y-450x300-450x300.jpg',
        name: 'Apple Macbook Pro Touch MPXX2SA/A ',
        price: '$1219',
        display: '13.3 inch, Retina (2560 x 1600)  ',
        dimensions: '304.1 mm - 212.4 mm -  14.9 mm ',
        os: 'Mac OS',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i5 Kabylake, 3.10 GHz',
        ram: '8 GB, DDR3L(On board), 2133 MHz ',
        memory: 'SSD: 256 GB',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2750 mAh'
    },


    {
        brand: 'laptop',
        id: 'lapmac5',
        img: 'img/laptop_apple/apple-macbook-pro-mpxt2sa-a-i5-7360u-tk-y.jpg',
        name: 'Macbook Pro MPXT2SA/A',
        price: '$1,619',
        display: '13.3 inch, Retina (2560 x 1600)  ',
        dimensions: '304.1 mm - 212.4 mm -  14.9 mm ',
        os: 'Mac OS',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i5 Kabylake, 2.30 GHz',
        ram: '8 GB, DDR3L(On board), 2133 MHz ',
        memory: 'SSD: 256 GB',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2750 mAh'
    },

    {
        brand: 'laptop',
        id: 'lapmac6',
        img: 'img/laptop_apple/apple-macbook-pro-15-mlh32sa-7.jpg',
        name: 'Macbook Pro Touch MPXV2SA/A i5',
        price: '$1,919',
        display: '13.3 inch, Retina (2560 x 1600)  ',
        dimensions: '304.1 mm - 212.4 mm -  14.9 mm ',
        os: 'Mac OS',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i5 Kabylake, 3.10 GHz',
        ram: '8 GB, DDR3L(On board), 2133 MHz ',
        memory: 'SSD: 256 GB',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2750 mAh'
    },

    {
        brand: 'laptop',
        id: 'lapmac7',
        img: 'img/laptop_apple/apple-macbook-pro-15-mlh32sa-7.jpg',
        name: 'Macbook Pro Touch MPXV2SA/A i7',
        price: '$2.189',
        display: '15.4 inch, Retina (2880 x 1800)   ',
        dimensions: '358 mm - 243 mm - 19 mm         ',
        os: 'Mac OS',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i7 Kabylake, 2.60 GHz',
        ram: '16 GB, DDR3L(On board), 2133 MHz ',
        memory: 'SSD: 256 GB',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Siri, Siri and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: '2750 mAh'
    },
    ////////////////////lapdell



    {
        brand: 'laptop',
        id: 'dell1',
        img: 'img/laptop_dell/dell-vostro-3468.png',
        name: 'Dell Vostro 3468',
        price: '$819',
        display: '14 inch, HD (1366 x 768)     ',
        dimensions: '358 mm - 243 mm - 19 mm         ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i5 Kabylake, 7200U, 2.50 GHz ',
        ram: '4 GB, DDR4 (2 khe), 2133 MHz   ',
        memory: 'HDD: 1 TB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 4 cell'
    },


    {
        brand: 'laptop',
        id: 'dell2',
        img: 'img/laptop_dell/dell-vostro-3568-i5-7200u-400-450x300-450x300.png',
        name: 'Dell Vostro 3568 i7 ',
        price: '$919',
        display: '15.6 inch, Full HD (1920 x 1080)     ',
        dimensions: '358 mm - 243 mm - 25 mm         ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i7 Kabylake, 7200U, 2.70 GHz ',
        ram: '4 GB, DDR4 (2 khe), 2400 MHz   ',
        memory: 'HDD: 1 TB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 4 cell'
    },

    {
        brand: 'laptop',
        id: 'dell3',
        img: 'img/laptop_dell/dell-vostro-3568-xf6c62-6-1.jpg',
        name: 'Dell Vostro 3768 i3 ',
        price: '$619',
        display: '14 inch, HD (1366 x 768)   ',
        dimensions: '358 mm - 243 mm - 25 mm         ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i7 Kabylake, 7200U, 2.40 GHz ',
        ram: '4 GB, DDR4 (2 khe), 2400 MHz   ',
        memory: 'HDD: 1 TB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 4 cell'
    },


    {
        brand: 'laptop',
        id: 'dell4',
        img: 'img/laptop_dell/dell-inspiron-7567-i7-7700hq-n7567a-den-dai-dien-450x300.jpg',
        name: 'Dell Inspiron 7460 i5 ',
        price: '$919',
        display: '14 inch, Full HD (1920 x 1080) ',
        dimensions: '358 mm - 243 mm - 18 mm         ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i7 Kabylake, 7200U, 2.50 GHz ',
        ram: '4 GB, DDR4 (2 khe), 2400 MHz   ',
        memory: 'HDD: 1 TB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 4 cell'
    },



    {
        brand: 'laptop',
        id: 'dell5',
        img: 'img/laptop_dell/dell-inspiron-5378-26w971-xam-1-h1-450x300-450x300.jpg',
        name: 'Dell Inspiron 5378 i5 ',
        price: '$919',
        display: '13.3 inch, Full HD (1920 x 1080)   ',
        dimensions: '358 mm - 243 mm - 19,5 mm         ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i7 Kabylake, 7200U, 2.50 GHz ',
        ram: '4 GB, DDR4 (2 khe), 2400 MHz   ',
        memory: 'SSD: 128 GB      ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 6 cell'
    },


    {
        brand: 'laptop',
        id: 'dell6',
        img: 'img/laptop_dell/dell-inspiron-7567-i7-7700hq-n7567a-den-dai-dien-450x300.jpg',
        name: 'Dell Inspiron 7567B i7 ',
        price: '$1319',
        display: '15.6 inch, 4K/UHD (3840 x 2160)    ',
        dimensions: '358 mm - 243 mm - 25,6 mm         ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i7 Kabylake, 7700HQ, 2.80 GHz',
        ram: '8 GB, DDR4 (2 khe), 2400 MHz   ',
        memory: 'HDD: 1 TB + SSD: 128GB      ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 6 cell'
    },


    {
        brand: 'laptop',
        id: 'dell7',
        img: 'img/laptop_dell/Dell Inspiron 3567.png',
        name: 'Dell Inspiron 3567 i3',
        price: '$419',
        display: '15.6 inch, HD (1366 x 768)   ',
        dimensions: '358 mm - 243 mm - 25 mm         ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i3 Skylake, 6006U, 2.00 GHz ',
        ram: '4 GB, DDR4 (2 khe), 2.400 MHz   ',
        memory: 'HDD: 1 TB      ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 4 cell'
    },


    {
        brand: 'laptop',
        id: 'dell8',
        img: 'img/laptop_dell/dell-inspiron-7373-i7-8550u-8gb-256gb-win10-dai-dien-1-450x300.jpg',
        name: 'Dell Inspiron 7373 i7',
        price: '$1519',
        display: '13.3 inch, Full HD (1920 x 1080)    ',
        dimensions: '358 mm - 243 mm - 25 mm         ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i7 Kabylake Refresh, 8550U, 1.80 GHz ',
        ram: '8 GB, DDR4 (2 khe), 2400 MHz    ',
        memory: 'SSD: 256 GB       ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 4 cell'
    },


    ///////////////////////////////////////////////////////// lenovo


    {
        brand: 'laptop',
        id: 'le01',
        img: 'img/laptop_lenovo/lenovo-ideapad-120s-11iap-450x300-1-450x300.jpg',
        name: 'Lenovo IdeaPad 120S 11IAP',
        price: '$219',
        display: '11.6 inch, HD (1366 x 768) ',
        dimensions: '238 mm - 203 mm - 20 mm  ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Celeron, N3350, 1.10 GHz  ',
        ram: '2 GB, DDR4 (On board), 2400 MHz  ',
        memory: 'eMMC: 32 GB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 4 cell'
    },





    {
        brand: 'laptop',
        id: 'le02',
        img: 'img/laptop_lenovo/lenovo-ideapad-110-14ibr-n3710-80t600ajvn-dai-dien-450x300.jpg',
        name: 'Lenovo Ideapad 110 14IBR N3710',
        price: '$319',
        display: '14 inch, HD (1366 x 768) ',
        dimensions: '338 mm - 243 mm - 20 mm  ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Pentium, N3710, 1.60 GHz  ',
        ram: '4 GB, DDR3L(On board), 1600 MHz    ',
        memory: 'HDD: 500 GB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 5 cell'
    },


    {
        brand: 'laptop',
        id: 'le03',
        img: 'img/laptop_lenovo/lenovo-ideapad-110-14ibr-n3710-80t600ajvn-dai-dien-450x300.jpg',
        name: 'Lenovo IdeaPad 110 15IBR N3710',
        price: '$389',
        display: '14.6 inch, HD (1366 x 768) ',
        dimensions: '388 mm - 263 mm - 22 mm  ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Pentium, N3710, 1.60 GHz  ',
        ram: '4 GB, DDR3L(On board), 1600 MHz    ',
        memory: 'HDD: 500 GB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 5 cell'
    },



    {
        brand: 'laptop',
        id: 'le04',
        img: 'img/laptop_lenovo/lenovo-ideapad-110-15ibr-80t700bkvn-den-h-450x300-450x300.jpg',
        name: 'Lenovo IdeaPad 110 15ISK i3 ',
        price: '$429',
        display: '15.6 inch, Full HD (1920 x 1080) ',
        dimensions: '388 mm - 243 mm - 23 mm  ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i3 Skylake, 6006U, 2.00 GHz  ',
        ram: '4 GB, DDR3L(On board), 2133 MHz    ',
        memory: 'HDD: 1 TB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 5 cell'
    },



    {
        brand: 'laptop',
        id: 'le05',
        img: 'img/laptop_lenovo/lenovo-yoga-520-14ikb-i3-7130u-8080106vn-3.jpg',
        name: 'Lenovo Yoga 520 14IKB i3 ',
        price: '$549',
        display: '14 inch, HD (1366 x 768)s ',
        dimensions: '358 mm - 243 mm - 20 mm ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i3 Kabylake, 7130U, 2.70 GHz  ',
        ram: '4 GB, DDR3L(On board), 2133 MHz    ',
        memory: 'HDD: 500 GB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 5 cell'
    },


    {
        brand: 'laptop',
        id: 'le06',
        img: 'img/laptop_lenovo/lenovo-thinkpad-13-i7-7500u-450x300-450x300.jpg',
        name: 'Lenovo ThinkPad 13 i7 ',
        price: '$1020',
        display: '13.3 inch, Full HD (1920 x 1080) ',
        dimensions: '328 mm - 243 mm - 19 mm   ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i7 Kabylake, 7500U, 2.70 GHz  ',
        ram: '8 GB, DDR4 (2 khe), 2400 MHz   ',
        memory: 'SSD: 256 GB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 6 cell'
    },

    {
        brand: 'laptop',
        id: 'le07',
        img: 'img/laptop_lenovo/lenovo-yoga-520-14ikb-i3-7130u-8080106vn-450x300.jpg',
        name: ' Lenovo Legion Y520 15IKBN i7 ',
        price: '$1220',
        display: '15.6 inch, Full HD (1920 x 1080) ',
        dimensions: '328 mm - 243 mm - 19 mm   ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i7 Kabylake, 7700HQ, 2.80 GHz  ',
        ram: '8 GB, DDR4 (2 khe), 2400 MHz   ',
        memory: 'HDD: 1 TB + SSD: 128GB  ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 6 cell'
    },

    {
        brand: 'laptop',
        id: 'le08',
        img: 'img/laptop_lenovo/lenovo-yoga-900-13isk-i7-6500u-450x300-300x300.jpg',
        name: ' Lenovo Yoga 900-13ISK i7 ',
        price: '$810',
        display: '13.3 inch, QHD+ (3200 x 1800) ',
        dimensions: '318 mm - 223 mm - 14 mm   ',
        os: 'Windows 10',
        camera: '5 MP ',
        videocall: 'yes',
        video_recording: '1080px video recording at 30 fps',
        cpu: 'Intel Core i7 Skylake, 6500U, 2.50 GHz   ',
        ram: '8 GB, DDR3 (on board), 1866 MHz   ',
        memory: 'SSD: 256 GB ',
        sim_card: 'No',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'Li-Ion 5 cell'
    },


    /////////////////////Tv_Sony/////////////////////////////////////////////////////////////////////////



    {
        brand: 'tv',
        id: 'tvsn01',
        img: 'img/tv_sony/tivi-sony-kdl-48w650d-550x340.jpg',
        name: ' Internet Tivi Sony 48 inch',
        price: '$659',
        display: 'Full HD 48 inch',
        dimensions: '109.2 cm - 64.3 cm - 6.6 cm  ',
        os: 'Linux',
        camera: 'None ',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },


    {
        brand: 'tv',
        id: 'tvsn02',
        img: 'img/tv_sony/tivi-sony-kd-49x8000e-thumb-550x340.png',
        name: 'Android Tivi Sony 49 inch',
        price: '$959',
        display: 'Ultra HD 4K 49 inch',
        dimensions: '109.6 cm - 64 cm - 5.7 cm  ',
        os: 'Android Tv',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },


    {
        brand: 'tv',
        id: 'tvsn03',
        img: 'img/tv_sony/tivisony-kd-55x8000e-s-550x340.png',
        name: 'Android Tivi Sony 4K 55 inch',
        price: '$1359',
        display: 'Ultra HD 4K 55 inch',
        dimensions: '129.6 cm - 72 cm - 5.7 cm  ',
        os: 'Android Tv',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },


    {
        brand: 'tv',
        id: 'tvsn04',
        img: 'img/tv_sony/tivi-sony-kd-49x8000e-thumb-550x340.png',
        name: 'Android tivi Sony 49 inch KD',
        price: '$859',
        display: 'Ultra HD 4K 49 inch',
        dimensions: '129.6 cm - 72 cm - 5.7 cm  ',
        os: 'Android Tv',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },




    {
        brand: 'tv',
        id: 'tvsn05',
        img: 'img/tv_sony/tivi-oled-sony-kd-65a1-550x340.png',
        name: 'Android Tivi OLED Sony 4K',
        price: '$3459',
        display: 'Ultra HD 4K 65 inch ',
        dimensions: '149.6 cm - 84 cm - 8.7 cm  ',
        os: 'Android Tv',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },


    {
        brand: 'tv',
        id: 'tvsn06',
        img: 'img/tv_sony/tivi-sony-kdl-40r350e-uplai-550x340.png',
        name: 'Tivi Sony 40 inch KDL-40R350D',
        price: '$359',
        display: 'Full HD 40 inch ',
        dimensions: '99.6 cm - 54 cm - 7.7 cm  ',
        os: 'Android Tv',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },




    {
        brand: 'tv',
        id: 'tvsn07',
        img: 'img/tv_sony/smart-tivi-sony-kd-55x8500d-s-2-550x340.jpg',
        name: 'Android Tivi Sony 55 inch KD',
        price: '$1259',
        display: 'Ultra HD 4K 55 inch ',
        dimensions: '129.6 cm - 74 cm - 4.7 cm',
        os: 'Android Tv',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },



    {
        brand: 'tv',
        id: 'tvsn08',
        img: 'img/tv_sony/tivi-sony-kdl-40r350d-550x340.jpg',
        name: 'Tivi Sony 40 inch KDL-40R350E',
        price: '$459',
        display: 'Full HD 40 inch ',
        dimensions: '92.6 cm - 54 cm - 6.7 cm',
        os: 'Android Tv',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },



    {
        brand: 'tv',
        id: 'tvsn09',
        img: 'img/tv_sony/tivi-led-sony-kdl-32r300e-uplai-550x340.png',
        name: 'Tivi Sony 32 inch KDL-32R300E',
        price: '$259',
        display: 'HD 32 inch ',
        dimensions: '73.6 cm - 43 cm - 6.4 cm',
        os: 'Android Tv',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },

    /////////////////////////tv_LG////////////////////////////////


    {
        brand: 'tv',
        id: 'tvlg01',
        img: 'img/tv_lg/tivi-led-lg-55uj632t-1-550x340.png',
        name: 'Smart Tivi LG 4K 55 inch',
        price: '$859',
        display: 'Ultra HD 4K 55 inch ',
        dimensions: '124 cm - 72 cm - 7 cm',
        os: 'Android Tv',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },


    {
        brand: 'tv',
        id: 'tvlg02',
        img: 'img/tv_lg/tivilg-49lj553t-1-550x340.png',
        name: 'Smart Tivi LG 49 inch 49LJ553T',
        price: '$559',
        display: 'Full HD 49 inch ',
        dimensions: '1110 cm - 62 cm - 7 cm',
        os: 'Web OS',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },



    {
        brand: 'tv',
        id: 'tvlg03',
        img: 'img/tv_lg/tivi-lg-32lj510d-thiein-550x340.png',
        name: 'Tivi LG 32 inch 32LJ510D',
        price: '$259',
        display: 'HD 32 inch',
        dimensions: '75 cm - 42 cm - 17 cm',
        os: 'Web OS',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },


    {
        brand: 'tv',
        id: 'tvlg04',
        img: 'img/tv_lg/tivi-lg-43lj510t-550x340.png',
        name: 'Tivi LG 43 inch 43LH511T',
        price: '$459',
        display: 'Full HD 43 inch',
        dimensions: '90 cm - 62 cm - 8 cm',
        os: 'Web OS',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },


    {
        brand: 'tv',
        id: 'tvlg05',
        img: 'img/tv_lg/tivi-led-lg-43lh511t-2-550x340.jpeg',
        name: 'TTivi LG 43 inch 43LJ510T',
        price: '$479',
        display: 'Full HD 43 inch',
        dimensions: '90 cm - 62 cm - 8 cm',
        os: 'Web OS',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },


    {
        brand: 'tv',
        id: 'tvlg06',
        img: 'img/tv_lg/tivioled-lg-55eg9a7t-fhd1-550x340.png',
        name: 'Smart Tivi OLED LG 55EG9A7T(FHD)',
        price: '$1259',
        display: 'Full HD OLED 55 inch ',
        dimensions: '123 cm - 72 cm - 5 cm',
        os: 'Web OS',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },



    {
        brand: 'tv',
        id: 'tvlg07',
        img: 'img/tv_lg/tivi-lg-65sj850t-thumb-550x340.png',
        name: 'Smart Tivi LG 65 inch 65SJ850',
        price: '$2959',
        display: 'Ultra HD 4K 65 inch ',
        dimensions: '143 cm - 82 cm - 5 cm',
        os: 'Web OS',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },



    {
        brand: 'tv',
        id: 'tvlg08',
        img: 'img/tv_lg/tivi-oled-lg-77w7t-550x340.png',
        name: 'Smart Tivi OLED LG 77 inch 77W7T',
        price: '$19959',
        display: 'Ultra HD 4K 77 inch ',
        dimensions: '173 cm - 92 cm - 5 cm',
        os: 'Web OS',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },


    //////////////////////////////Tv panasonic///////////////////////////////////////////

    {
        brand: 'tv',
        id: 'tvpa01',
        img: 'img/tv_panasonic/tivi-panasonic-th-49ex600v-daidien--550x340.png',
        name: 'Smart Tivi Panasonic 49 inch TH-49EX600V',
        price: '$659',
        display: 'Ultra HD 4 K 49 inch ',
        dimensions: '123 cm - 62 cm - 8 cm',
        os: 'My Home Screen',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },



    {
        brand: 'tv',
        id: 'tvpa02',
        img: 'img/tv_panasonic/tivi-panasonic-th-32es500v-13-550x340.jpg',
        name: 'Smart Tivi Panasonic 32 inch TH-32ES500V',
        price: '$359',
        display: 'HD 32 inch  ',
        dimensions: '83 cm - 52 cm - 8 cm',
        os: 'My Home Screen',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },




    {
        brand: 'tv',
        id: 'tvpa03',
        img: 'img/tv_panasonic/tivi-panasonic-th-50ex750v-550x340.png',
        name: 'Smart Tivi Panasonic 49 inch TH-49ES500V',
        price: '$579',
        display: 'Full HD 49 inch  ',
        dimensions: '78 cm - 62 cm - 8 cm',
        os: 'My Home Screen',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },



    {
        brand: 'tv',
        id: 'tvpa04',
        img: 'img/tv_panasonic/tivi-panasonic-th-40e400v-uplai-550x340.png',
        name: 'Tivi Panasonic 40 inch TH-40E400V',
        price: '$379',
        display: 'Full HD 40 inch  ',
        dimensions: '85 cm - 62 cm - 13 cm',
        os: 'My Home Screen',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },



    {
        brand: 'tv',
        id: 'tvpa05',
        img: 'img/tv_panasonic/tivi-panasonic-th-49es500v-thumb-550x340.png',
        name: 'Smart Tivi Panasonic 49 inch TH_49E410V',
        price: '$579',
        display: 'Full HD 49 inch  ',
        dimensions: '98 cm - 72 cm - 12 cm',
        os: 'My Home Screen',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },


    {
        brand: 'tv',
        id: 'tvpa06',
        img: 'img/tv_panasonic/panasonic-th-50ex750v-3-org.jpg',
        name: 'Smart Tivi Panasonic 4K 50 inch TH-50EX750V',
        price: '$879',
        display: 'Ultra HD 4K 50 inch   ',
        dimensions: '123 cm - 62 cm - 8 cm',
        os: 'My Home Screen',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },



    {
        brand: 'tv',
        id: 'tvpa07',
        img: 'img/tv_panasonic/panasonic-th-55ez950v-1-1-550x340.png',
        name: 'Smart Tivi OLED Panasonic 55 inch TH-55EZ950V',
        price: '$2879',
        display: 'Ultra HD 4K 55 inch   ',
        dimensions: '136 cm - 90 cm - 6 cm',
        os: 'My Home Screen',
        camera: 'None',
        videocall: 'None',
        video_recording: 'None',
        cpu: ' None',
        ram: ' None',
        memory: 'None ',
        sim_card: 'None',
        wifi: 'Wi-Fi 802.11 a/b/g/n/ac, Dual-band, DLNA, Wi-Fi Direct, Wi-Fi hotspot',
        audio_and_video: 'MP4, AVI, WMV, H.263, H.264(MPEG4-AVC), DivX, MP3, WAV, WMA',
        accessibility: 'VoiceOver,Zoom,Magnifier, Software TTY, Switch Control, Type to Windown, Windown and Dictation, Closed Captions,Speak Screen',
        headphones_jack: '3.5 mm',
        battery: 'None'
    },



];